version: '3.8'

services:
  app:
    image: golang:1.23
    container_name: auth_app
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=auth
      - JWT_SECRET_KEY=Auth$3cureKey2023!
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      go mod tidy &&
      go run main.go
      "

  db:
    image: mysql:8.0.36
    container_name: auth_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: