// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github/com/Gajju8989/Auth_Service/internal/handler"
	"github/com/Gajju8989/Auth_Service/internal/repo"
	"github/com/Gajju8989/Auth_Service/internal/router"
	"github/com/Gajju8989/Auth_Service/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthService(db *gorm.DB) (router.MapRouter, error) {
	repository := repo.NewRepository(db)
	authService, err := service.NewAuthService(repository)
	if err != nil {
		return nil, err
	}
	handlerHandler := handler.NewHandler(authService)
	mapRouter := router.NewRouter(handlerHandler)
	return mapRouter, nil
}
